In [1]:
#TODO 1. Fragen und Antworten übersetzen
# 2. max. Punkte für Antworten vergeben
# 3. Schlüsselbegriffe herausfiltern
# 4. Klassifizierung (Abfrage, Hauptfrage, Ergänzungsfrage)

In [2]:
#Datei einlesen
import pandas as pd
from llm_handler import LLMHandler

path = "../raw/DataScienceBasics_QandA - Sheet1.csv"
df = pd.read_csv(path)
df.head()

,Id,Question,Answer
0,1,What is data science?,Data science is an interdisciplinary field tha...
1,2,What are the key steps in the data science pro...,The key steps typically include problem defini...
2,3,What is the difference between supervised and ...,Supervised learning involves training a model ...
3,4,Explain the bias-variance tradeoff.,The bias-variance tradeoff is the balance betw...
4,5,What is feature engineering?,Feature engineering is the process of selectin...

In [3]:
#Prompt schreiben

def construct_prompt(question, answer):
    return f"""Du bist professioneller Übersetzer vom Englischen ins Deutsche.
    Übersetze die englische Frage {question} und die dazugehörige Antwort {answer} bestmöglich ins Deutsche.
    Halte dich dabei kurz und erfinde nichts dazu. Gib die Übersetzung im angegebenen Antwortformat zurück.

    <Antwortformat>
    ```json
    {{
        "question": "<Die übersetzte Frage vom Englischen ins Deutsche>",
        "answer": "<Die übersetzte Antwort vom Englischen ins Deutsche>"
    }}```
    """

In [4]:
#LLM aufrufen und in Dataframe speichern

llm = LLMHandler()
result_list = []

for index, row in df.iterrows():
  prompt = construct_prompt(row["Question"],row["Answer"])
  answer = llm.call_llm(prompt)
  answer["original_question"] = row["Question"]
  answer["original_answer"] = row["Answer"]
  result_list.append(answer)
  break

process_data = pd.DataFrame(result_list)

In [5]:
#Daten CSV speichern

#process_data.to_csv("generated_q_and_a.csv")

process_data.head()

,question,answer,original_question,original_answer
0,Was ist Data Science?,Data Science ist ein interdisziplinäres Fachge...,What is data science?,Data science is an interdisciplinary field tha...